jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      musl:
        BUILD: musl
    maxParallel: 5
  steps:
  - bash: echo "##vso[task.setvariable variable=TAG]${BUILD_SOURCEBRANCH##refs/tags/}"
    displayName: Set TAG variable
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  - script: |
      docker image build . -t tldr
      # https://github.com/moby/moby/issues/34592#issuecomment-331001595
      CID=$(docker create tldr)
      docker cp ${CID}:/app/tldr .
      docker rm ${CID}
      echo "musl build"
      ls
      ls -lh ./tldr
      cp ./tldr $(Build.ArtifactStagingDirectory)
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
  - task: ArchiveFiles@2
    inputs:
      includeRootFolder: false
      archiveType: tar
      tarCompression: gz
      archiveFile: $(Build.ArtifactStagingDirectory)/tldr-musl-linux-$(TAG).tar.gz
      verbose: true
    condition: and(startsWith(variables['TAG'], 'v'), eq(variables['DEPLOY'], '1'))
  - task: GithubRelease@0
    displayName: Create GitHub Release
    inputs:
      githubConnection: github.com_psibi
      assets: $(Build.ArtifactStagingDirectory)/tldr-linux-$(TAG).tar.gz
      assetUploadMode: replace
      action: edit
      tag: $(TAG)
    condition: and(startsWith(variables['TAG'], 'v'), eq(variables['DEPLOY'], '1'))
