jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      musl:
        BUILD: musl
    maxParallel: 5
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      docker image build . -t tldr
      # https://github.com/moby/moby/issues/34592#issuecomment-331001595
      CID=$(docker create tldr)
      docker cp ${CID}:/app/tldr .
      docker rm ${CID}
      echo "musl build"
      ls
      ls -lh ./tldr
      cp ./tldr $(Build.ArtifactStagingDirectory)
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/tldr
    artifactName: tldr-musl
