jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-def:
        BUILD: stack
        STACK_YAML: stack.yaml
    maxParallel: 2
  steps:
  - bash: |
      chcp 65001
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-i386 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack --install-ghc $ARGS test --bench --only-dependencies
      # stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps Todo: fix windows build
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
  - bash: ./.azure/build_release.sh
    displayName: Build Release
  - task: ArchiveFiles@2
    inputs:
      includeRootFolder: false
      archiveType: tar
      tarCompression: gz
      archiveFile: $(Build.ArtifactStagingDirectory)/tldr-osx-$(TAG).tar.gz
      verbose: true
    condition: startsWith(variables['TAG'], 'v')
  - task: GithubRelease@0
    displayName: Create GitHub Release
    inputs:
      githubConnection: github.com_psibi
      assets: $(Build.ArtifactStagingDirectory)/tldr-osx-$(TAG).tar.gz
      assetUploadMode: replace
      action: edit
      tag: $(TAG)
    condition: startsWith(variables['TAG'], 'v')
